version: "3"

services:
  web:
    build: .
    container_name: sentinela
    image: sentinela  
    command: npm run start:dev
    volumes:
      - './:/app'
    ports:
      - "3000:3000"
    depends_on: 
      - banco-dados

  banco-dados:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5433:5432"
    volumes:
      - dados-banco:/var/lib/postgresql/data

volumes: 
  dados-banco:
